config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lessons
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointed_language.rb
class AppointedLanguage < ApplicationRecord
  belongs_to :user_id
  belongs_to :language_id
end

app/models/definition.rb
class Definition < ApplicationRecord
  belongs_to :language_id
  belongs_to :user_id
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  belongs_to :language
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: %i[show destroy edit update]

  def index
    @lessons = policy_scope(Lesson)
  end

  def new
    @lesson = Lesson.new
    authorize @lesson
  end

  def create
    @lesson = Lesson.new(lesson_params)
    authorize @lesson
    @lesson.language_id = 1
    @less.user_id = current_user.id

    if @lesson.save
      redirect_to lesson_path(@lesson)
    else
      # redirect_to lists_path
      puts "############### ERROR #{@lesson.errors.full_messages}"
      render 'new'
    end
  end

  def show
    @pages = []
    @lesson.text.split('.').each { |page| @pages << page }
  end

  def edit
  end

  def destroy
    @lesson.destroy
    redirect_to lessons_path
  end

  def update
    if @lesson.save
      redirect_to lesson_path(@lesson)
    else
      # redirect_to lists_path
      puts "############### ERROR #{@lesson.errors.full_messages}"
      render 'new'
    end
  end

  private

  def lesson_params
    params.require(:lesson).permit(:title, :difficulty_level, :text)
  end

  def set_lesson
    @lesson = Lesson.find(params[:id])
    authorize @lesson
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Definiendum</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'turn_pages', defer: true %>


  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/lessons/index.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div class="flex justify-center bg-green-100 p-4">
  <div class="w-3/4">
    <div class="max-w-sm w-full lg:max-w-full lg:flex m-5">
      <div class="h-48 lg:h-auto lg:w-48 flex-none bg-cover rounded-t lg:rounded-t-none lg:rounded-l text-center overflow-hidden" style="background-image: url(<%= image_path('card-left') %>)" title="Woman holding a mug">
      </div>
      <div class="border-r border-b border-l border-gray-400 lg:border-l-0 lg:border-t lg:border-gray-400 bg-white rounded-b lg:rounded-b-none lg:rounded-r p-4 flex flex-col justify-between leading-normal">
        <div class="mb-8">
          <div class="text-gray-900 font-bold text-xl mb-2">Can coffee make you a better developer?</div>
          <p class="text-gray-700 text-base">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.</p>
        </div>
      </div>
    </div>
    <div class="max-w-sm w-full lg:max-w-full lg:flex m-5">
      <div class="h-48 lg:h-auto lg:w-48 flex-none bg-cover rounded-t lg:rounded-t-none lg:rounded-l text-center overflow-hidden" style="background-image: url(<%= image_path('card-left') %>)" title="Woman holding a mug">
      </div>
      <div class="border-r border-b border-l border-gray-400 lg:border-l-0 lg:border-t lg:border-gray-400 bg-white rounded-b lg:rounded-b-none lg:rounded-r p-4 flex flex-col justify-between leading-normal">
        <div class="mb-8">
          <div class="text-gray-900 font-bold text-xl mb-2">Can coffee make you a better developer?</div>
          <p class="text-gray-700 text-base">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.</p>
        </div>
      </div>
    </div>
    <div class="max-w-sm w-full lg:max-w-full lg:flex m-5">
      <div class="h-48 lg:h-auto lg:w-48 flex-none bg-cover rounded-t lg:rounded-t-none lg:rounded-l text-center overflow-hidden" style="background-image: url(<%= image_path('card-left') %>)" title="Woman holding a mug">
      </div>
      <div class="border-r border-b border-l border-gray-400 lg:border-l-0 lg:border-t lg:border-gray-400 bg-white rounded-b lg:rounded-b-none lg:rounded-r p-4 flex flex-col justify-between leading-normal">
        <div class="mb-8">
          <div class="text-gray-900 font-bold text-xl mb-2">Can coffee make you a better developer?</div>
          <p class="text-gray-700 text-base">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.</p>
        </div>
      </div>
    </div>
    <div class="max-w-sm w-full lg:max-w-full lg:flex m-5">
      <div class="h-48 lg:h-auto lg:w-48 flex-none bg-cover rounded-t lg:rounded-t-none lg:rounded-l text-center overflow-hidden" style="background-image: url(<%= image_path('card-left') %>)" title="Woman holding a mug">
      </div>
      <div class="border-r border-b border-l border-gray-400 lg:border-l-0 lg:border-t lg:border-gray-400 bg-white rounded-b lg:rounded-b-none lg:rounded-r p-4 flex flex-col justify-between leading-normal">
        <div class="mb-8">
          <div class="text-gray-900 font-bold text-xl mb-2">Can coffee make you a better developer?</div>
          <p class="text-gray-700 text-base">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.</p>
        </div>
      </div>
    </div>
    <div class="max-w-sm w-full lg:max-w-full lg:flex m-5">
      <div class="h-48 lg:h-auto lg:w-48 flex-none bg-cover rounded-t lg:rounded-t-none lg:rounded-l text-center overflow-hidden" style="background-image: url(<%= image_path('card-left') %>)" title="Woman holding a mug">
      </div>
      <div class="border-r border-b border-l border-gray-400 lg:border-l-0 lg:border-t lg:border-gray-400 bg-white rounded-b lg:rounded-b-none lg:rounded-r p-4 flex flex-col justify-between leading-normal">
        <div class="mb-8">
          <div class="text-gray-900 font-bold text-xl mb-2">Can coffee make you a better developer?</div>
          <p class="text-gray-700 text-base">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.</p>
        </div>
      </div>
    </div>
    <div class="max-w-sm w-full lg:max-w-full lg:flex m-5">
      <div class="h-48 lg:h-auto lg:w-48 flex-none bg-cover rounded-t lg:rounded-t-none lg:rounded-l text-center overflow-hidden" style="background-image: url(<%= image_path('card-left') %>)" title="Woman holding a mug">
      </div>
      <div class="border-r border-b border-l border-gray-400 lg:border-l-0 lg:border-t lg:border-gray-400 bg-white rounded-b lg:rounded-b-none lg:rounded-r p-4 flex flex-col justify-between leading-normal">
        <div class="mb-8">
          <div class="text-gray-900 font-bold text-xl mb-2">Can coffee make you a better developer?</div>
          <p class="text-gray-700 text-base">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.</p>
        </div>
      </div>
    </div>
    <div class="max-w-sm w-full lg:max-w-full lg:flex m-5">
      <div class="h-48 lg:h-auto lg:w-48 flex-none bg-cover rounded-t lg:rounded-t-none lg:rounded-l text-center overflow-hidden" style="background-image: url(<%= image_path('card-left') %>)" title="Woman holding a mug">
      </div>
      <div class="border-r border-b border-l border-gray-400 lg:border-l-0 lg:border-t lg:border-gray-400 bg-white rounded-b lg:rounded-b-none lg:rounded-r p-4 flex flex-col justify-between leading-normal">
        <div class="mb-8">
          <div class="text-gray-900 font-bold text-xl mb-2">Can coffee make you a better developer?</div>
          <p class="text-gray-700 text-base">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.</p>
        </div>
      </div>
    </div>
    <div class="max-w-sm w-full lg:max-w-full lg:flex m-5">
      <div class="h-48 lg:h-auto lg:w-48 flex-none bg-cover rounded-t lg:rounded-t-none lg:rounded-l text-center overflow-hidden" style="background-image: url(<%= image_path('card-left') %>)" title="Woman holding a mug">
      </div>
      <div class="border-r border-b border-l border-gray-400 lg:border-l-0 lg:border-t lg:border-gray-400 bg-white rounded-b lg:rounded-b-none lg:rounded-r p-4 flex flex-col justify-between leading-normal">
        <div class="mb-8">
          <div class="text-gray-900 font-bold text-xl mb-2">Can coffee make you a better developer?</div>
          <p class="text-gray-700 text-base">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.</p>
        </div>
      </div>
    </div>
    <div class="max-w-sm w-full lg:max-w-full lg:flex m-5">
      <div class="h-48 lg:h-auto lg:w-48 flex-none bg-cover rounded-t lg:rounded-t-none lg:rounded-l text-center overflow-hidden" style="background-image: url(<%= image_path('card-left') %>)" title="Woman holding a mug">
      </div>
      <div class="border-r border-b border-l border-gray-400 lg:border-l-0 lg:border-t lg:border-gray-400 bg-white rounded-b lg:rounded-b-none lg:rounded-r p-4 flex flex-col justify-between leading-normal">
        <div class="mb-8">
          <div class="text-gray-900 font-bold text-xl mb-2">Can coffee make you a better developer?</div>
          <p class="text-gray-700 text-base">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/lessons/new.html.erb
<div class="flex justify-center mt-10">
  <div class="w-3/4 xl:w-1/2">
    <%= simple_form_for @lesson do |f| %>
      <%= f.input :title %>
      <%= f.input :difficulty_level %>
      <%= f.input :text %>
      <%= f.button :submit %>
    <% end %>
  </div>
</div>

app/views/lessons/show.html.erb
<div class="flex remaining-height w-screen">
  <div class="hidden w-1/6 md:block lg:block xl:block bg-gray-200 border-r-2 shadow-lg mr-2">
    <div class="p-2"><%= image_tag 'card-left', class: 'rounded-xl' %></div>
    <div class="p-4 text-xl font-bold"><%= @lesson.title %></div>
  </div>
  <div class="flex flex-row w-5/6 text-xl">
    <div class="flex flex-col justify-center text-4xl p-12 cursor-pointer bg-green-100 hover:bg-green-200 duration-500 border shadow-lg rounded-xl border-black m-3" id="back"><i class="fas fa-chevron-left"></i></div>
    <div class="px-12 flex-grow py-12" id="page_1">
      <%= simple_format(@pages[0] + ".") %>
    </div>
    <% @pages.each_with_index do |page, i| %>
      <% unless i == 0 %>
        <div class="hidden flex-grow py-12" id="page_<%= i + 1 %>"><%= simple_format(page + ".") %></div>
      <% end %>
    <% end %>
    <div class="flex flex-col justify-center text-4xl p-12 cursor-pointer bg-green-100 hover:bg-green-200 duration-500 border shadow-lg rounded-xl border-black m-3" id="next"><i class="fas fa-chevron-right"></i></div>
  </div>
</div>



<div class="hidden min-w-screen h-screen animated fadeIn faster  fixed  left-0 top-0 flex justify-center items-center inset-0 z-50 outline-none focus:outline-none bg-no-repeat bg-center bg-cover" id="modal">
  <div class="absolute bg-black opacity-80 inset-0 z-0"></div>
    <div class="w-full  max-w-lg p-5 relative mx-auto my-auto rounded-xl shadow-lg  bg-white ">
      <div class="">
        <div class="text-center p-5 flex-auto justify-center">
          <h2 class="text-xl font-bold py-4" id="selected"></h2>
          <p class="text-sm text-gray-500 px-8" id="definition"></p>
        </div>
        <div class="p-3 mt-2 text-center space-x-4 md:block">
          <button class="mb-2 md:mb-0 bg-white px-5 py-2 text-sm shadow-sm font-medium tracking-wider border text-gray-600 rounded-full hover:shadow-lg hover:bg-gray-100" id="cancel">Cancel</button>
          <button class="mb-2 md:mb-0 bg-red-500 border border-red-500 px-5 py-2 text-sm shadow-sm font-medium tracking-wider text-white rounded-full hover:shadow-lg hover:bg-red-600" id="select">Select Definition</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar sticky top-0 z-50">
  <div class="max-w-full mx-auto px-4 md:px-8 md:pt-1 pb-1">
    <div class="flex justify-between">

      <div class="flex space-x-4">
        <!-- logo -->
        <div>
          <a href="/lessons" class="flex items-center py-4 hover:text-gray-900">
            <i class="fas fa-language text-gray-100 text-3xl md:text-4xl"></i>
            <span class="logo-text text-gray-100 font-bold text-2xl md:text-4xl pl-4">Definiendum</span>
          </a>
        </div>
      </div>

      <!-- new lesson, login, sign up, profile -->
      <div class="hidden sm:flex items-center justify-between space-x-2">
        <% if user_signed_in? %>
          <a href="<%= new_lesson_path %>" class="nav-link text-lg py-5 pr-3 hover:text-yellow-400"><i class="far fa-plus-square text-xl mr-1"></i>New Lesson</a>
          <%= link_to 'Sign Out', destroy_user_session_path, class: "nav-link text-lg py-5 px-3 hover:text-yellow-400", method: :delete, data: { confirm: "You really want to sign out?",  } %>
          <%#= link_to current_user.first_name, profile_path(current_user.profile), class: "text-lg py-2 px-3 bg-yellow-400 hover:bg-yellow-300 text-yellow-900 hover:text-yellow-800 rounded transition duration-300" %>
        <% else %>
          <%= link_to 'Login', new_user_session_path, class: "nav-link text-lg py-5 px-3 hover:text-yellow-400" %>
          <%= link_to 'Sign Up', new_user_registration_path, class: "text-lg py-2 px-3 hover:bg-yellow-400 bg-yellow-500 text-black hover:text-black rounded transition duration-200" %>
        <% end %>
      </div>

      <!-- hamburger button for mobile -->
      <div class="sm:hidden flex items-center">
        <button class="mobile-menu-button">
          <i class="fas fa-bars text-2xl text-yellow-300 hover:text-yellow-400"></i>
        </button>
      </div>

    </div>
  </div>

  <!-- categories bar MOBILE -->
  <div class="mobile-menu hidden sm:hidden pb-3">
    <div class="flex items-center justify-center space-x-2">
      <% if user_signed_in? %>
        <%= link_to 'New Lesson', new_lesson_path, class: "nav-link text-md hover:text-yellow-300 py-5 px-3" %>
        <%= link_to 'Sign Out', destroy_user_session_path, class: "nav-link text-md hover:text-yellow-300 py-5 px-3", method: :delete, data: { confirm: "You really want to sign out?",  } %>
        <%#= link_to current_user.first_name, profile_path(current_user.profile), class: "text-lg py-1 px-2 bg-yellow-400 hover:bg-yellow-300 text-yellow-900 hover:text-yellow-800 rounded transition duration-300" %>
      <% else %>
        <%= link_to 'Login', new_user_session_path, class: "nav-link text-md hover:text-yellow-300 py-5 px-3" %>
        <%= link_to 'Sign Up', new_user_registration_path, class: "text-md py-1 px-2 bg-yellow-400 hover:bg-yellow-300 text-yellow-900 hover:text-yellow-800 rounded transition duration-300" %>
      <% end %>
    </div>
    <%= link_to 'All', lessons_path, class: "nav-link block py-2 px-4 text-sm text-center tracking-wider hover:text-yellow-900 hover:bg-yellow-200 hover:font-bold" %>
  </div>
</nav>